version: '3.4'

services:
  stt-api:
    build:
      context: .
      dockerfile: ./Dockerfile.flask
    ports:
      - 5000:5000

  stt-web:
    build: 
      context: .
      dockerfile: ./Dockerfile.react
    ports:
      - 3000:3000
    depends_on:
      - stt-api